chore: add labels to docker image
jenkins-infra/ldap pull request #27
Opened 2021-02-10 09:40 UTC by garethjevans

2021-02-10 10:17 UTC, olblak approved these changes

2021-02-10 16:08 UTC, garethjevans commented
I don't have permission to merge this one @olblak

2021-02-12 15:36 UTC, dduportal approved these changes
LGTM 👍

2021-02-12 15:36 UTC, dduportal commented
Neither do I :(

2021-02-15 13:23 UTC, olblak commented
I just gave write permission to the group jenkins-infra/docker so next time you should be able to merge it @dduportal @garethjevans

2021-02-15 13:25 UTC, olblak requested changes

2021-02-15 13:26 UTC, garethjevans commented on Makefile
> +BUILD_DATE     := $(shell date --utc '+%Y-%m-%dT%H:%M:%S' 2>/dev/null || gdate --utc '+%Y-%m-%dT%H:%M:%S')
good point, i'll fix that now

2021-02-15 13:33 UTC, olblak approved these changes

2021-02-15 13:33 UTC, merged